version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: python manage.py runserver 0.0.0.0:8080

  scheduler1:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    command: sh -c "sleep 20 && python Alerts/scheduler.py"

  scheduler2:
    build:
      context: .
      dockerfile: Dockerfile.phase2_scheduler
    command: sh -c "sleep 25 && python Alerts/phase2_scheduler.py"
