# Generated by Django 4.0.4 on 2023-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_phrase', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('frequency', models.IntegerField()),
            ],
        ),
    ]
